name: Test

on:
  push:
  workflow_dispatch:
    inputs:
      ref:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Display inputs
        run: ${{ toJson(inputs) }}
        shell: jq --color-output . {0}

      - name: Fetch ${{ inputs.ref }} (new)
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          ref: ${{ inputs.ref }}

      - name: Fetch ${{ inputs.ref }} (old)
        if: always()
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
